version: '2'
services:
  #  teamcity-server:
  #    image: teamcity-server:local-linux
  #    ports:
  #      - "8112:8111"

  teamcity-minimal-agent:
    image: teamcity-minimal-agent:EAP-linux
    environment:
      - SERVER_URL=teamcity-server:8111

  teamcity-agent:
    image: teamcity-agent:EAP-linux
    environment:
      - SERVER_URL=teamcity-server:8111

#  teamcity-agent-sudo:
#    image: teamcity-agent:local-linux-sudo
#    privileged: true
#    environment:
#      - SERVER_URL=teamcity-server:8111
#      - DOCKER_IN_DOCKER=start